### ISSUE TITLE
[Inference] output file destination

### ISSUE THREAD

**Issue by delhomer** [delhomer/kpconv-torch#11]
When doing inference, one writes outputs near to the dataset folder (given by `-d`), while one could write them near to the input file (given by `-f`), or even elsewhere.

Additional point: separating the output folder from the dataset folder makes the dataset parameter (`-d`) useless in the inference command. (related issue: #9).

**Comment by AuBousquet** [comment]
https://github.com/delhomer/kpconv-torch/pull/22
